### ISSUE TITLE
Fix SVG shape positioning

### ISSUE THREAD

**Issue by timhwang21** [a-trost/newhavenio#13]
One solution is to remove the max width, and have each "box" have width of 100%, with non-blob children being in a separate node with a consistent max width. Then the box can set `overflow: hidden`.

**Comment by a-trost** [comment]
We'll also want to make sure each of the triangles are centered to the viewport so that the shift doesn't happen when going to smaller screens.

**Comment by timhwang21** [comment]
@a-trost halp plz

I think one possible solution would be to make each _section_ have a width of 100%, and a set amount of (media-responsive) padding. So rather than having a page-level container with a max width, the max widths would be section level.

This is a bit non-DRY, but would let us just do `overflow: hidden;` on the sections, and to put the shapes within the sections themselves. I can take a crack at this as well.
