### ISSUE TITLE
Core components

### ISSUE THREAD

**Issue by timhwang21** [a-trost/newhavenio#3]
- ~Button~
  - Primary (orange)
  - Secondary (blue)
  - Tertiary (white)
- Link
- Typography
- ~Logo~
- ~Card~
- Icon
- ~Datetime~
- ~Footer~

**Comment by a-trost** [comment]
Are we separating out more specific components into a different list? (eg: Event Cards)

**Comment by timhwang21** [comment]
Yeah, that was my plan. Might make sense to put button, etc. in a `core/` directory. Then the other top level stuff within `components/` will be molecules.
