### ISSUE TITLE
refactor: reconcile breakpoints

### ISSUE THREAD

**Issue by timhwang21** [a-trost/newhavenio#46]
We ended up with two duplicate breakpoint systems.

**Comment by codybarr** [comment]
I implemented the "second" breakpoint system, which hooks into `styled-system`'s configuration for them.

I believe the original breakpoint system was included as part of the starter. If it's OK with everybody I think we should just use `styled-system`'s breakpoint system.

We're only using the other one in two files currently: `src/components/shared/title/title.css.js` and `src/components/shared/inviteform/inviteform.css.js`.

I could work on this one.

**Comment by timhwang21** [comment]
SGTM! I'm not opiniated.

One thought is that I somewhat prefer pixel based breakpoints since that's more in line with what I think are industry standards, but I may be wrong. The 414 / 768 / 1024 / 1408 system is one I see a lot.
