### ISSUE TITLE
feat(Events): Zapier integration

### ISSUE THREAD

**Issue by timhwang21** [a-trost/newhavenio#48]
1. Setup official Zapier API keys / account for repo
2. Create Meetup event webhook: https://zapier.com/apps/meetup/integrations/webhook
3. Trigger a Netlify site rebuild via POST

**Comment by timhwang21** [comment]
@a-trost you want to handle this one? Probably easiest since you have all the credentials.

Maybe it's worth all of us sharing our password managers so we can share secrets for this project?

**Comment by a-trost** [comment]
Just set this up with https://stdlib.com/ as it seems more developer-focused than Zapier. 

Set to build every morning at 4:00 AM. The nice thing about Standard Library is they give you the building blocks to connect Slack, SMS, etc. but also give you access to the underlying code. You can't really peek under the hood of Zapier's actions. 

I'd like to figure out how we can notify a specific Slack channel if a build fails. It might be useful. 

I shared @timhwang21 on my LastPass account for this - happy to share anyone else.

**Comment by timhwang21** [comment]
Awesome!!

Though one nice thing with zapier is allegedly you can build in response to
events, so instead of scheduling a daily build we just build on demand when
a new event is created (or a new blog posts are updated, etc.).

**Comment by a-trost** [comment]
The only issue comes with the events. We either need to build those on the fly or we need to build routinely. Until this morning the top Event was -6 days until event start. I'm good either way. Right now this seems the easiest way.
