### ISSUE TITLE
feat(About): Team info

### ISSUE THREAD

**Issue by timhwang21** [a-trost/newhavenio#50]
- [ ] Contact members, get information (however much team wants to provide)
  - Slack handle
  - Github
  - Email
  - Linkedin 
  - Twitter
  - ...?

**Comment by Quinncuatro** [comment]
I have at least this for you right now:

Henry Quinn | @henry | henry@newhaven.io
Jenn Nolte | @Jenn Nolte she/her | jenn@newhaven.io
Josh Levinson | @jlevnhv | josh@newhaven.io
Steve Voils | @steve | steve@newhaven.io
Tom Reznick | @tom | tom@newhaven.io
Ben Midyette | @ben | ben@newhaven.io

Put out a call to action for headshots, blurbs, and whatever anyone wants to share past that ^^

**Comment by timhwang21** [comment]
Thanks! I think headshots and stuff can come later - can you also provide role? (Prez, VP etc.)

**Comment by Quinncuatro** [comment]
There may be some slight changes to this format. I'll chime back in after the board meeting.

**Comment by Quinncuatro** [comment]
Can we add email addresses to the team page?

henry@newhaven.io
tom@newhaven.io
josh@newhaven.io
steve@newhaven.io
ben@newhaven.io
jenn@newhaven.io

**Comment by timhwang21** [comment]
Hm, pushing back on this a bit: what's the use case for emailing an individual vs. having a shared board@newhaven.io? Seems like needing to constantly rotate out email addresses increases the possibility of stale addresses without much benefit, and would avoid the need for people to forward emails back and forth if an email needs input of multiple people. If we had a single address we can also just build a contact form right into the page, which seems like the lowest friction way to reach out.

**Comment by Quinncuatro** [comment]
Fair enough. We have a few of those to pick from.

organizers@newhaven.io
abuse@newhaven.io
conduct@newhaven.io

All are aliases that hit all of our inboxes.
