### ISSUE TITLE
feat(Copy): Copy for various pages

### ISSUE THREAD

**Issue by timhwang21** [a-trost/newhavenio#52]
# Home

- [x] Need a brief elevator pitch blurb, maybe 2 sentences, right under 'Where tech happens in New Haven'.
- [x] Sensible blurbs for Slack

# About

- [x] Summarize content from https://newhaven.io/about/ (and https://newhaven.io/ and https://newhaven.io/blog/what-is-NewHavenIO/, somewhat).

**Comment by Quinncuatro** [comment]
What do you mean "sensible blurbs for slack"?

**Comment by Quinncuatro** [comment]
Gonna word vomit in here for a bit.

**Comment by Quinncuatro** [comment]
Instead of "Where tech happens in New Haven." maybe "The water cooler of the New Haven tech scene."

**Comment by timhwang21** [comment]
Sensible blurb = replacing the lorum ipsum (possibly with nothing if we don't need more description).

I sort of like the water cooler thing as specifically describing Slack maybe?

**Comment by Quinncuatro** [comment]
```
Where tech happens in New Haven.

NewHaven.io is a tech community that helps each other learn, solve problems, and connect with the local tech scene.
```

I'm into water cooler bit describing Slack.
