### ISSUE TITLE
feat(Maintainers)

### ISSUE THREAD

**Issue by timhwang21** [a-trost/newhavenio#64]
We likely need a page listing active maintainers. Not for bragging rights or anything, but to document who currently has access to API keys, credentials for stuff like Netlify, etc.

It might also make sense to have an official NHIO 1Pass or something.

**Comment by Quinncuatro** [comment]
Is this different than Issue #86 ?

**Comment by timhwang21** [comment]
Yeah, I envision this being a page on the site itself. So people viewing the site can see how to get involved.

Maybe making the READMEs good would be sufficient but I'm worried about discoverability.

**Comment by Quinncuatro** [comment]
I think the readme will be fine. Anyone wanting to know how to change the code will likely be looking at the code, yeah?

Unless y'all just want your names on it. 😉
