### ISSUE TITLE
Slack invite

### ISSUE THREAD

**Issue by timhwang21** [a-trost/newhavenio#8]
We either need to get access to New Haven IO's slack credentials if we want to make our own widget, or we should reuse the one here: https://newhavenio-slackin.herokuapp.com/iframe?large

We have to iframe it, which makes styling it awkward. But might be a future enhancement.

**Comment by a-trost** [comment]
We're already using Netlify for the site hosting (So far at least) so we can leverage their built-in lambdas with this: https://github.com/kylemcd/marketers-chat/blob/1a2689e89bfa0277a2ae459a864751e196e73af5/src/lambda/slackSubmit.js

Seems like a cleaner solution, but there might be an issue with bots? Not sure.

**Comment by timhwang21** [comment]
Wooo cloud functions >>>> hacky iframe solution!
